const SUPABASE_URL = "https://hfyavvbummqkalugzago.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmeWF2dmJ1bW1xa2FsdWd6YWdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDc1MzAsImV4cCI6MjA2NzI4MzUzMH0.mB9Cgl0HZWItw2ItXeFuZAMP8vjXrpGc8juHgB-jfY0";
const supabase = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
